version: '3.7'
services:        
    poc_db:
        image: microsoft/mssql-server-windows-express
        ports:
            - "1433:1433"
        environment:
            - "sa_password=@dam93!Nis1323"
            - "ACCEPT_EULA=Y"
        networks:
            poc_network:
                ipv4_address: 172.28.1.3
    poc_rabbitmq:
        image: micdenny/rabbitmq-windows
        hostname: poc-rabbitmq
        networks:
            poc_network:
                ipv4_address: 172.28.1.10
networks:
    poc_network:
        ipam:
            config:
                - subnet: 172.28.0.0/16
            
         